### ISSUE TITLE
App gets stuck if permission is revoked

### ISSUE THREAD

**Issue by DSOTM-pf** [hgdev-ch/toposuite-android#2]
Hi, there, I found TopoSuite_v1.2.0 (downloaded from F-Droid) getting stuck if the permission is denied.

### Reproduce bug
1. enter the app and allow the permission request
2. go the "Jobs" page, this page functions are normally
3. go to the system setting and revoke the storage permission
4. back to app and the app gets stuck

Here is the video about how I found this stuck.

https://user-images.githubusercontent.com/26241319/127281702-a98ba2bb-9114-4d4b-8cd9-35aacedf863d.mp4

@rolinh 
Could you help me review this issue? Very Thanks!!!

**Comment by rolinh** [comment]
Hi, thanks for the bug report. I'm not sure how such a case should be handled but getting stuck is indeed not a desired behavior.

**Comment by rolinh** [comment]
Fixed with version [v1.4.0-beta.4](https://github.com/hgdev-ch/toposuite-android/releases/tag/v1.4.0-beta.4) which does not require any permissions anymore.
